steps:
  - name: 'gcr.io/google.com/cloudsdktool/google-cloud-cli'
    entrypoint: 'gcloud'
    args:
      - 'alpha'
      - 'run'
      - 'compose'
      - 'up'
      - '--project=app-factory-v2'
      - '--region=us-central1'
    dir: 'backend'
options:
  logging: CLOUD_LOGGING_ONLY