steps:
  - name: 'gcr.io/google.com/cloudsdktool/google-cloud-cli'
    entrypoint: 'bash'
    args:
      - '-c'
      - 'apt-get update && apt-get install -y google-cloud-cli-run-compose && gcloud alpha run compose up --project=app-factory-v2 --region=us-central1'
    dir: 'backend'
options:
  logging: CLOUD_LOGGING_ONLY